server:
  hostname: http://localhost:8080
mongodb:
  database: interview_dev
  url: mongodb+srv://admin:78jGbjNvyE7SQvXF@adv-sdlxm.mongodb.net/{db}?retryWrites=true&w=majority
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1
            clientSecret: 2
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: cd385ed810a44ab378c7
            clientSecret: 60403e5ddf2b5411fde6d27875b8b73c94403e03
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
cloudinary:
  cloudName: dmswg6dq2
  apiKey: 831934641529161
  apiSecret: 5l7HTn6c0SIhXypMxICm_OolnJc
security:
  jwt:
    expirationTime: 864000000
  oauth2:
    authorizedRedirectUrl: http://localhost:4200/social
  cors:
    allowedOrigin: http://localhost:4200