mongodb:
  database: test_db
  url: mongodb+srv://admin:78jGbjNvyE7SQvXF@adv-sdlxm.mongodb.net/{db}?retryWrites=true&w=majority
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
cloudinary:
  cloudName: dmswg6dq2
  apiKey: 831934641529161
  apiSecret: 5l7HTn6c0SIhXypMxICm_OolnJc