server:
  hostname: https://interview-prep-app.herokuapp.com/
mongodb:
  database: code_interview_prod
  url: ${MONGO_URL}
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
cloudinary:
  cloudName: dmswg6dq2
  apiKey: 831934641529161
  apiSecret: 5l7HTn6c0SIhXypMxICm_OolnJc
security:
  jwt:
    expirationTime: 864000000