server:
  hostname: http://localhost:8080
mongodb:
  database: test_db
  url: mongodb+srv://admin:78jGbjNvyE7SQvXF@adv-sdlxm.mongodb.net/{db}?retryWrites=true&w=majority
cloudinary:
  cloudName: dmswg6dq2
  apiKey: 831934641529161
  apiSecret: 5l7HTn6c0SIhXypMxICm_OolnJc
security:
  jwt:
    expirationTime: 864000000
  oauth2:
    authorizedRedirectUrl: http://localhost:4200/social
  cors:
    allowedOrigin: http://localhost:4200